// *** Parser rules ***

grammar: rule*

rule: RULE_NAME ":" rule_body ";"

rule_body: rule_part+ ("|" rule_part+)*

rule_part: rule_elem [suffix]

?rule_elem: "(" rule_body ")" | RULE_NAME | TOKEN_NAME | TOKEN_LIT

?suffix: PLUS | STAR | QUEST_MARK

// *** Lexer rules ***

PLUS: "+"
STAR: "*"
QUEST_MARK: "?"

TOKEN_NAME: /[A-Z][A-Z0-9_]*/
RULE_NAME: /[a-z][a-z0-9_]*/
TOKEN_LIT: "\"" /.*?/ "\""

WS: /[ \t\f\r\n]/+
COMMENT: /#[^\r\n]*/
%ignore COMMENT
%ignore WS
